# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: arXiv-daily-ai-enhanced

on:
  # Runs at 01:05 UTC every Monday, Tuesday, Wednesday, Thursday, Friday.
  # This time is chosen because the arXiv daily announcement/listing update happens at 20:00 US Eastern Time (Sun-Thu),
  # which corresponds to either 00:00 UTC or 01:00 UTC (Mon-Fri) depending on US Daylight Saving Time.
  # Running at 01:05 UTC ensures the script executes *after* the announcement is complete in *all* cases,
  # guaranteeing access to the full list of papers for the day.
  schedule:
    - cron: "05 01 * * 1-5"
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        uv sync
    - name: Run script
      run: |
        source .venv/bin/activate
        export OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
        export OPENAI_BASE_URL=${{ secrets.OPENAI_BASE_URL }}
        export LANGUAGE="${{ vars.LANGUAGE }}"
        export CATEGORIES="${{ vars.CATEGORIES }}"
        export MODEL_NAME="${{ vars.MODEL_NAME }}"
        bash run.sh
    - name: get date
      id: get_date
      run: |
        echo "CURRENT_DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV
    - name: commit
      run: |
        git config --global user.email "${{ vars.EMAIL }}"
        git config --global user.name "${{ vars.NAME }}"
        git add .
        git commit -m "update ${{ env.CURRENT_DATE }}"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
